filebeat.inputs:
- type: container
  paths: 
     - '/var/lib/docker/containers/*/*.log'
  json.keys_under_root: true

processors:
  - decode_json_fields:
      fields: ["message"]

  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
      
  - drop_fields:
      fields: ["container.labels"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"