version: "3"
services:
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:${elasticVerion}"
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

    kibana:
        image: "docker.elastic.co/kibana/kibana:${elasticVerion}"
        ports:
            - "5601:5601"

    filebeat:
        image: "docker.elastic.co/beats/filebeat:${elasticVerion}"
        user: root
        ## asdcommand: filebeat -e -strict.perms=false
        volumes:
            - ./Filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/containers:/var/lib/docker/containers

volumes:
    elasticsearch_data: